services:
  payment-gateway-database:
    container_name: payment-gateway-database
    image: bitnami/mongodb:latest
    restart: always
    ports:
      - 27017:27017
    networks:
      - payment-gateway-network
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=payment-gateway-database
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=root
      - MONGODB_DATABASE=payment-gateway-database
      - MONGODB_ROOT_USERNAME=root
      - MONGODB_ROOT_PASSWORD=root

  payment-gateway:
    build: .
    image: payment/payment-gateway
    container_name: payment-gateway
    restart: always
    networks:
      - payment-gateway-network
    ports:
      - "8080:8080"
    environment:
      - MONGO_DB_HOST=payment-gateway-database
      - MONGO_DB_URI=mongodb://root:root@payment-gateway-database/payment-gateway-database?retryWrites=true&w=majority
      - MONGODB_DATABASE=payment-gateway-database
      - MONGODB_ROOT_USERNAME=root
      - MONGODB_ROOT_PASSWORD=root
      - MONGODB_PORT=27017
      - CREDIT_CARD_ENDPOINT=http://credit-card-service:8081
      - PAYPAL_ENDPOINT=http://paypal-service:8082
    depends_on:
      - payment-gateway-database

networks:
  payment-gateway-network:
    name: payment-gateway-network